name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8.15.0

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Install Studio dependencies
        run: |
          cd studio
          pnpm install --frozen-lockfile

      - name: Build project
        run: pnpm run build

      - name: Run tests (if any)
        run: pnpm run test || echo "No test script found, skipping tests"

      - name: Publish to npm
        run: |
          if [[ "${{ github.ref_name }}" == *"canary"* ]]; then
            pnpm publish --access public --tag canary --no-git-checks
          else
            pnpm publish --access public --no-git-checks
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: |
            ${{ contains(github.ref_name, 'canary') && 'Canary Release' || 'Release' }} ${{ github.ref_name }}
          body: |
            ## What's Changed

            See [CHANGELOG.md](./CHANGELOG.md) for full details.

            ## Installation

            ```bash
            ${{ contains(github.ref_name, 'canary') && format('npm install lithia@canary  # or npm install lithia@{0}', github.ref_name) || format('npm install lithia@{0}', github.ref_name) }}
            ```
          draft: false
          prerelease: ${{ contains(github.ref_name, 'canary') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
