name: Release

on:
  push:
    tags:
      - 'v*'
      - '*-canary*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build project
        run: pnpm run build

      - name: Run tests (if any)
        run: pnpm run test || echo "No test script found, skipping tests"

      - name: Publish to npm
        run: |
          if [[ "${{ github.ref_name }}" == *"canary"* ]]; then
            pnpm publish --access public --tag canary
          else
            pnpm publish --access public
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: |
            ${{ contains(github.ref_name, 'canary') && 'Canary Release' || 'Release' }} ${{ github.ref }}
          body: |
            ## What's Changed

            See [CHANGELOG.md](./CHANGELOG.md) for full details.

            ## Installation

            ```bash
            npm install lithia@${{ github.ref_name }}
            ```
          draft: false
          prerelease: false
